import type { Product, Category, Testimonial, PaymentMethod, NavItem, CategoryGroup } from '@/types';

export const navItems: NavItem[] = [
  { label: 'Gaming', href: '/store/group/gaming' },
  { label: 'AI Tools VIP', href: '/store/group/ai-tools' },
  { label: 'Streaming & Cards', href: '/store/group/streaming' },
  { label: 'Deals', href: '/store' },
];

// Gaming Categories
export const gamingCategories: Category[] = [
  {
    id: 'steam',
    name: 'Steam',
    slug: 'steam',
    image: '/images/categories/gaming.jpg',
    icon: 'Gamepad2',
    productCount: 156,
  },
  {
    id: 'playstation',
    name: 'PlayStation',
    slug: 'playstation',
    image: '/images/categories/gaming.jpg',
    icon: 'Gamepad2',
    productCount: 89,
  },
  {
    id: 'xbox',
    name: 'Xbox',
    slug: 'xbox',
    image: '/images/categories/gaming.jpg',
    icon: 'Gamepad2',
    productCount: 72,
  },
  {
    id: 'mobile-games',
    name: 'Mobile Games',
    slug: 'mobile-games',
    image: '/images/categories/mobile-games.jpg',
    icon: 'Smartphone',
    productCount: 234,
  },
  {
    id: 'nintendo',
    name: 'Nintendo',
    slug: 'nintendo',
    image: '/images/categories/gaming.jpg',
    icon: 'Gamepad2',
    productCount: 45,
  },
  {
    id: 'pc-games',
    name: 'PC Games',
    slug: 'pc-games',
    image: '/images/categories/gaming.jpg',
    icon: 'Monitor',
    productCount: 312,
  },
];

// AI Tools Categories
export const aiToolsCategories: Category[] = [
  {
    id: 'ai-chat-search',
    name: 'AI Chat & Search',
    slug: 'ai-chat-search',
    image: '/images/categories/ai-tools.jpg',
    icon: 'MessageSquare',
    productCount: 18,
  },
  {
    id: 'ai-image-design',
    name: 'AI Image & Design',
    slug: 'ai-image-design',
    image: '/images/categories/ai-tools.jpg',
    icon: 'Image',
    productCount: 24,
  },
  {
    id: 'ai-video-audio',
    name: 'AI Video & Audio',
    slug: 'ai-video-audio',
    image: '/images/categories/ai-tools.jpg',
    icon: 'Video',
    productCount: 20,
  },
  {
    id: 'ai-writing',
    name: 'AI Writing',
    slug: 'ai-writing',
    image: '/images/categories/ai-tools.jpg',
    icon: 'PenTool',
    productCount: 15,
  },
  {
    id: 'ai-developer',
    name: 'AI Developer Tools',
    slug: 'ai-developer',
    image: '/images/categories/ai-tools.jpg',
    icon: 'Code',
    productCount: 16,
  },
  {
    id: 'ai-productivity',
    name: 'AI Productivity',
    slug: 'ai-productivity',
    image: '/images/categories/ai-tools.jpg',
    icon: 'Zap',
    productCount: 14,
  },
];

// Streaming & Gift Cards Categories
export const streamingCategories: Category[] = [
  {
    id: 'streaming',
    name: 'Streaming',
    slug: 'streaming',
    image: '/images/categories/streaming.jpg',
    icon: 'Play',
    productCount: 45,
  },
  {
    id: 'gift-cards',
    name: 'Gift Cards',
    slug: 'gift-cards',
    image: '/images/categories/gift-cards.jpg',
    icon: 'Gift',
    productCount: 178,
  },
  {
    id: 'music',
    name: 'Music',
    slug: 'music',
    image: '/images/categories/streaming.jpg',
    icon: 'Music',
    productCount: 32,
  },
  {
    id: 'software',
    name: 'Software',
    slug: 'software',
    image: '/images/categories/gift-cards.jpg',
    icon: 'Box',
    productCount: 67,
  },
];

// Category Groups for display
export const categoryGroups: CategoryGroup[] = [
  {
    id: 'gaming',
    title: 'Gaming',
    subtitle: 'Game top-ups, subscriptions, and in-game currency',
    categories: gamingCategories,
  },
  {
    id: 'ai-tools',
    title: 'AI Tools VIP',
    subtitle: 'Premium AI subscriptions for every need',
    categories: aiToolsCategories,
  },
  {
    id: 'streaming',
    title: 'Streaming & Gift Cards',
    subtitle: 'Entertainment subscriptions and digital gift cards',
    categories: streamingCategories,
  },
];

// Gaming Products
export const gamingProducts: Product[] = [
  {
    id: 'g1',
    name: 'Steam Wallet $50',
    description: 'Add $50 to your Steam Wallet instantly',
    price: 45.99,
    originalPrice: 50.00,
    image: '/images/categories/gaming.jpg',
    category: 'steam',
    platform: 'Steam',
    region: 'Global',
    rating: 4.9,
    reviewCount: 2847,
    badge: '8% OFF',
    instantDelivery: true,
  },
  {
    id: 'g2',
    name: 'Xbox Game Pass Ultimate 3 Month',
    description: '3 months of Xbox Game Pass Ultimate',
    price: 29.99,
    originalPrice: 44.99,
    image: '/images/categories/gaming.jpg',
    category: 'xbox',
    platform: 'Xbox',
    region: 'Global',
    rating: 4.8,
    reviewCount: 1523,
    badge: '33% OFF',
    instantDelivery: true,
  },
  {
    id: 'g3',
    name: 'PlayStation Plus Essential 12 Month',
    description: '12 months PlayStation Plus Essential membership',
    price: 59.99,
    originalPrice: 79.99,
    image: '/images/categories/gaming.jpg',
    category: 'playstation',
    platform: 'PlayStation',
    region: 'Global',
    rating: 4.7,
    reviewCount: 2104,
    badge: '25% OFF',
    instantDelivery: true,
  },
  {
    id: 'g4',
    name: 'Genshin Impact Genesis Crystals 6480',
    description: '6480 Genesis Crystals for Genshin Impact',
    price: 99.99,
    originalPrice: 109.99,
    image: '/images/categories/mobile-games.jpg',
    category: 'mobile-games',
    platform: 'Mobile',
    region: 'Global',
    rating: 4.8,
    reviewCount: 1567,
    badge: '9% OFF',
    instantDelivery: true,
  },
];

// AI Chat & Search Products
export const aiChatSearchProducts: Product[] = [
  {
    id: 'ai1',
    name: 'ChatGPT Plus 1 Month',
    description: 'Full access to GPT-4, DALL-E, and advanced features',
    price: 20.00,
    image: '/images/categories/ai-tools.jpg',
    category: 'ai-chat-search',
    platform: 'OpenAI',
    region: 'Global',
    rating: 4.9,
    reviewCount: 5421,
    instantDelivery: true,
  },
  {
    id: 'ai2',
    name: 'ChatGPT Plus 12 Month',
    description: 'Annual subscription with best value',
    price: 199.00,
    originalPrice: 240.00,
    image: '/images/categories/ai-tools.jpg',
    category: 'ai-chat-search',
    platform: 'OpenAI',
    region: 'Global',
    rating: 4.9,
    reviewCount: 3210,
    badge: '17% OFF',
    instantDelivery: true,
  },
  {
    id: 'ai3',
    name: 'Claude Pro 1 Month',
    description: 'Access to Claude 3.5 Sonnet with higher limits',
    price: 20.00,
    image: '/images/categories/ai-tools.jpg',
    category: 'ai-chat-search',
    platform: 'Anthropic',
    region: 'Global',
    rating: 4.8,
    reviewCount: 1892,
    instantDelivery: true,
  },
  {
    id: 'ai4',
    name: 'Gemini Advanced 1 Month',
    description: 'Google\'s most capable AI model',
    price: 19.99,
    image: '/images/categories/ai-tools.jpg',
    category: 'ai-chat-search',
    platform: 'Google',
    region: 'Global',
    rating: 4.7,
    reviewCount: 1234,
    instantDelivery: true,
  },
  {
    id: 'ai5',
    name: 'Perplexity Pro 1 Month',
    description: 'AI-powered search with real-time information',
    price: 20.00,
    image: '/images/categories/ai-tools.jpg',
    category: 'ai-chat-search',
    platform: 'Perplexity',
    region: 'Global',
    rating: 4.8,
    reviewCount: 876,
    instantDelivery: true,
  },
];

// AI Image & Design Products
export const aiImageDesignProducts: Product[] = [
  {
    id: 'img1',
    name: 'Midjourney Basic Plan',
    description: '200 GPU minutes per month',
    price: 10.00,
    image: '/images/categories/ai-tools.jpg',
    category: 'ai-image-design',
    platform: 'Midjourney',
    region: 'Global',
    rating: 4.9,
    reviewCount: 3421,
    instantDelivery: true,
  },
  {
    id: 'img2',
    name: 'Midjourney Standard Plan',
    description: '15 hours GPU time with unlimited relax',
    price: 30.00,
    image: '/images/categories/ai-tools.jpg',
    category: 'ai-image-design',
    platform: 'Midjourney',
    region: 'Global',
    rating: 4.9,
    reviewCount: 2156,
    instantDelivery: true,
  },
  {
    id: 'img3',
    name: 'Leonardo AI Pro 1 Month',
    description: 'Unlimited image generation',
    price: 12.00,
    image: '/images/categories/ai-tools.jpg',
    category: 'ai-image-design',
    platform: 'Leonardo AI',
    region: 'Global',
    rating: 4.7,
    reviewCount: 987,
    instantDelivery: true,
  },
  {
    id: 'img4',
    name: 'Canva Pro 1 Year',
    description: 'Full access to premium templates and AI features',
    price: 99.99,
    originalPrice: 119.99,
    image: '/images/categories/ai-tools.jpg',
    category: 'ai-image-design',
    platform: 'Canva',
    region: 'Global',
    rating: 4.8,
    reviewCount: 5432,
    badge: '17% OFF',
    instantDelivery: true,
  },
  {
    id: 'img5',
    name: 'Playground AI Pro',
    description: 'Unlimited AI image generation',
    price: 15.00,
    image: '/images/categories/ai-tools.jpg',
    category: 'ai-image-design',
    platform: 'Playground AI',
    region: 'Global',
    rating: 4.6,
    reviewCount: 654,
    instantDelivery: true,
  },
];

// AI Video & Audio Products
export const aiVideoAudioProducts: Product[] = [
  {
    id: 'vid1',
    name: 'Runway Gen-3 Standard',
    description: '625 credits per month for AI video generation',
    price: 28.00,
    image: '/images/categories/ai-tools.jpg',
    category: 'ai-video-audio',
    platform: 'Runway',
    region: 'Global',
    rating: 4.8,
    reviewCount: 1234,
    instantDelivery: true,
  },
  {
    id: 'vid2',
    name: 'Pika Pro 1 Month',
    description: 'Unlimited video generation',
    price: 35.00,
    image: '/images/categories/ai-tools.jpg',
    category: 'ai-video-audio',
    platform: 'Pika',
    region: 'Global',
    rating: 4.7,
    reviewCount: 567,
    instantDelivery: true,
  },
  {
    id: 'vid3',
    name: 'ElevenLabs Starter',
    description: '30k characters per month for AI voice',
    price: 5.00,
    image: '/images/categories/ai-tools.jpg',
    category: 'ai-video-audio',
    platform: 'ElevenLabs',
    region: 'Global',
    rating: 4.9,
    reviewCount: 2134,
    instantDelivery: true,
  },
  {
    id: 'vid4',
    name: 'Synthesia Personal',
    description: '10 video credits per month',
    price: 22.00,
    image: '/images/categories/ai-tools.jpg',
    category: 'ai-video-audio',
    platform: 'Synthesia',
    region: 'Global',
    rating: 4.6,
    reviewCount: 876,
    instantDelivery: true,
  },
];

// AI Writing Products
export const aiWritingProducts: Product[] = [
  {
    id: 'w1',
    name: 'Jasper Boss Mode',
    description: 'Unlimited words with long-form assistant',
    price: 59.00,
    image: '/images/categories/ai-tools.jpg',
    category: 'ai-writing',
    platform: 'Jasper',
    region: 'Global',
    rating: 4.7,
    reviewCount: 1543,
    instantDelivery: true,
  },
  {
    id: 'w2',
    name: 'Writesonic Business',
    description: '200k words per month',
    price: 19.00,
    image: '/images/categories/ai-tools.jpg',
    category: 'ai-writing',
    platform: 'Writesonic',
    region: 'Global',
    rating: 4.6,
    reviewCount: 987,
    instantDelivery: true,
  },
  {
    id: 'w3',
    name: 'Copy.ai Pro',
    description: 'Unlimited words and projects',
    price: 36.00,
    image: '/images/categories/ai-tools.jpg',
    category: 'ai-writing',
    platform: 'Copy.ai',
    region: 'Global',
    rating: 4.5,
    reviewCount: 1234,
    instantDelivery: true,
  },
  {
    id: 'w4',
    name: 'Rytr Unlimited',
    description: 'Generate unlimited characters',
    price: 29.00,
    image: '/images/categories/ai-tools.jpg',
    category: 'ai-writing',
    platform: 'Rytr',
    region: 'Global',
    rating: 4.4,
    reviewCount: 654,
    instantDelivery: true,
  },
];

// AI Developer Tools Products
export const aiDeveloperProducts: Product[] = [
  {
    id: 'dev1',
    name: 'GitHub Copilot Individual',
    description: 'AI pair programmer for your IDE',
    price: 10.00,
    image: '/images/categories/ai-tools.jpg',
    category: 'ai-developer',
    platform: 'GitHub',
    region: 'Global',
    rating: 4.9,
    reviewCount: 8765,
    instantDelivery: true,
  },
  {
    id: 'dev2',
    name: 'Cursor Pro 1 Month',
    description: 'AI-first code editor with GPT-4',
    price: 20.00,
    image: '/images/categories/ai-tools.jpg',
    category: 'ai-developer',
    platform: 'Cursor',
    region: 'Global',
    rating: 4.8,
    reviewCount: 2134,
    instantDelivery: true,
  },
  {
    id: 'dev3',
    name: 'Replit Core 1 Month',
    description: 'AI-powered cloud development',
    price: 7.00,
    image: '/images/categories/ai-tools.jpg',
    category: 'ai-developer',
    platform: 'Replit',
    region: 'Global',
    rating: 4.6,
    reviewCount: 876,
    instantDelivery: true,
  },
  {
    id: 'dev4',
    name: 'Codeium Pro',
    description: 'Unlimited AI code completion',
    price: 12.00,
    image: '/images/categories/ai-tools.jpg',
    category: 'ai-developer',
    platform: 'Codeium',
    region: 'Global',
    rating: 4.7,
    reviewCount: 543,
    instantDelivery: true,
  },
];

// AI Productivity Products
export const aiProductivityProducts: Product[] = [
  {
    id: 'prod1',
    name: 'Notion AI Add-on',
    description: 'AI writing assistant for Notion',
    price: 10.00,
    image: '/images/categories/ai-tools.jpg',
    category: 'ai-productivity',
    platform: 'Notion',
    region: 'Global',
    rating: 4.8,
    reviewCount: 3456,
    instantDelivery: true,
  },
  {
    id: 'prod2',
    name: 'Gamma Plus 1 Month',
    description: 'AI-powered presentations',
    price: 15.00,
    image: '/images/categories/ai-tools.jpg',
    category: 'ai-productivity',
    platform: 'Gamma',
    region: 'Global',
    rating: 4.7,
    reviewCount: 654,
    instantDelivery: true,
  },
  {
    id: 'prod3',
    name: 'Tome Pro 1 Month',
    description: 'AI storytelling and presentations',
    price: 16.00,
    image: '/images/categories/ai-tools.jpg',
    category: 'ai-productivity',
    platform: 'Tome',
    region: 'Global',
    rating: 4.5,
    reviewCount: 432,
    instantDelivery: true,
  },
  {
    id: 'prod4',
    name: 'Taskade AI Pro',
    description: 'AI-powered task management',
    price: 19.00,
    image: '/images/categories/ai-tools.jpg',
    category: 'ai-productivity',
    platform: 'Taskade',
    region: 'Global',
    rating: 4.6,
    reviewCount: 321,
    instantDelivery: true,
  },
];

// All AI Products combined
export const aiToolsProducts: Product[] = [
  ...aiChatSearchProducts,
  ...aiImageDesignProducts,
  ...aiVideoAudioProducts,
  ...aiWritingProducts,
  ...aiDeveloperProducts,
  ...aiProductivityProducts,
];

// Streaming & Gift Cards Products
export const streamingProducts: Product[] = [
  {
    id: 's1',
    name: 'Netflix Gift Card $30',
    description: '$30 Netflix gift card for subscription',
    price: 28.50,
    originalPrice: 30.00,
    image: '/images/categories/streaming.jpg',
    category: 'streaming',
    platform: 'Netflix',
    region: 'Global',
    rating: 4.9,
    reviewCount: 4234,
    badge: '5% OFF',
    instantDelivery: true,
  },
  {
    id: 's2',
    name: 'Spotify Premium 3 Month',
    description: '3 months Spotify Premium subscription',
    price: 29.99,
    originalPrice: 32.97,
    image: '/images/categories/streaming.jpg',
    category: 'music',
    platform: 'Spotify',
    region: 'Global',
    rating: 4.7,
    reviewCount: 1876,
    badge: '9% OFF',
    instantDelivery: true,
  },
  {
    id: 's3',
    name: 'YouTube Premium 1 Month',
    description: 'Ad-free YouTube with background play',
    price: 11.99,
    image: '/images/categories/streaming.jpg',
    category: 'streaming',
    platform: 'YouTube',
    region: 'Global',
    rating: 4.8,
    reviewCount: 2341,
    instantDelivery: true,
  },
  {
    id: 's4',
    name: 'Amazon Gift Card $50',
    description: 'Universal Amazon gift card',
    price: 47.50,
    originalPrice: 50.00,
    image: '/images/categories/gift-cards.jpg',
    category: 'gift-cards',
    platform: 'Amazon',
    region: 'Global',
    rating: 4.9,
    reviewCount: 6543,
    badge: '5% OFF',
    instantDelivery: true,
  },
];

// All featured products (for homepage)
export const featuredProducts: Product[] = [
  ...gamingProducts,
  ...aiChatSearchProducts.slice(0, 2),
  ...aiImageDesignProducts.slice(0, 2),
  ...streamingProducts.slice(0, 2),
];

// All products
export const products: Product[] = [
  ...gamingProducts,
  ...aiToolsProducts,
  ...streamingProducts,
];

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Alex Mueller',
    location: 'Germany',
    avatar: 'AM',
    content: 'Fastest Steam top-up I\'ve ever used. Code arrived in my email within seconds. Highly recommended!',
    rating: 5,
  },
  {
    id: '2',
    name: 'Maria Silva',
    location: 'Brazil',
    avatar: 'MS',
    content: 'Finally a safe way to get ChatGPT Plus in my country. CrossMor handles everything professionally.',
    rating: 5,
  },
  {
    id: '3',
    name: 'James Wilson',
    location: 'United Kingdom',
    avatar: 'JW',
    content: 'The MOR model gives me peace of mind. I know I\'m dealing with a legitimate business.',
    rating: 5,
  },
  {
    id: '4',
    name: 'Yuki Tanaka',
    location: 'Japan',
    avatar: 'YT',
    content: 'Instant delivery, no hassle. The support team is also very responsive when I had questions.',
    rating: 5,
  },
  {
    id: '5',
    name: 'Carlos Rodriguez',
    location: 'Mexico',
    avatar: 'CR',
    content: 'Great prices on Xbox Game Pass. Saved over 30% compared to buying directly from Microsoft.',
    rating: 5,
  },
  {
    id: '6',
    name: 'Sophie Martin',
    location: 'France',
    avatar: 'SM',
    content: 'Customer support actually helps! Had an issue with my order and they resolved it within an hour.',
    rating: 5,
  },
];

export const paymentMethods: PaymentMethod[] = [
  { id: '1', name: 'Visa', icon: 'CreditCard' },
  { id: '2', name: 'Mastercard', icon: 'CreditCard' },
  { id: '3', name: 'PayPal', icon: 'Wallet' },
  { id: '4', name: 'Apple Pay', icon: 'Smartphone' },
  { id: '5', name: 'Google Pay', icon: 'Smartphone' },
  { id: '6', name: 'Alipay', icon: 'Wallet' },
  { id: '7', name: 'Crypto', icon: 'Bitcoin' },
];

export const stats = [
  { label: 'Happy Customers', value: 2, suffix: 'M+' },
  { label: 'Countries Served', value: 50, suffix: '+' },
  { label: 'Uptime', value: 99.9, suffix: '%', decimals: 1 },
  { label: 'Processed', value: 50, prefix: '$', suffix: 'M+' },
];

export const howItWorks = [
  {
    step: 1,
    title: 'Choose Your Product',
    description: 'Browse 1000+ digital goods from games to AI subscriptions',
    icon: 'Search',
  },
  {
    step: 2,
    title: 'Pay Securely',
    description: 'Multiple payment methods with encrypted transactions',
    icon: 'Shield',
  },
  {
    step: 3,
    title: 'Instant Delivery',
    description: 'Codes delivered to your email in seconds',
    icon: 'Zap',
  },
  {
    step: 4,
    title: 'Enjoy & Save',
    description: 'Activate and start using immediately',
    icon: 'Sparkles',
  },
];

export const trustFeatures = [
  {
    title: 'MOR Protection',
    description: 'We\'re the merchant of record, handling all tax and compliance for you.',
    icon: 'BadgeCheck',
  },
  {
    title: 'PCI DSS Compliant',
    description: 'Bank-level security for all transactions and data protection.',
    icon: 'Lock',
  },
  {
    title: 'Fraud Protection',
    description: 'AI-powered risk detection keeps your purchases safe.',
    icon: 'ShieldCheck',
  },
  {
    title: '24/7 Support',
    description: 'Real humans, real help, anytime you need assistance.',
    icon: 'Headphones',
  },
];
