import type { Product, CategoryGroup, Testimonial, PaymentMethod, NavItem } from '@/types';

// ─── Navigation ─────────────────────────────────────────────────────────────
export const navItems: NavItem[] = [
  { id: 'ai-digital-tools', labelKey: 'ai_tools', href: '/store/group/ai-digital-tools' },
  { id: 'streaming-entertainment', labelKey: 'streaming', href: '/store/group/streaming-entertainment' },
  { id: 'gift-cards-wallet', labelKey: 'gift_cards_wallet', href: '/store/group/gift-cards-wallet' },
  { id: 'software-saas', labelKey: 'software_saas', href: '/store/group/software-saas' },
  { id: 'regional-services', labelKey: 'regional_services', href: '/store/group/regional-services' },
  { id: 'deals', labelKey: 'deals', href: '/store' },
];

// ─── Category groups (top-level) + subcategories ─────────────────────────────
export const categoryGroups: CategoryGroup[] = [
  {
    id: 'ai-digital-tools',
    title: 'AI & Digital Tools',
    subtitle: 'Premium AI subscriptions and API credits',
    labelKey: 'ai_tools',
    image: '/images/categories/ai-digital-tools.jpg',
    categories: [
      {
        id: 'ai-subscriptions',
        name: 'AI & Digital Tools',
        slug: 'ai-digital-tools',
        image: '/images/categories/ai-subscriptions.jpg',
        icon: 'Brain',
        productCount: 6,
      },
    ],
  },
  {
    id: 'streaming-entertainment',
    title: 'Streaming & Entertainment',
    subtitle: 'Video and music subscriptions',
    labelKey: 'streaming',
    image: '/images/categories/streaming-entertainment.jpg',
    categories: [
      {
        id: 'streaming-subscriptions',
        name: 'Streaming & Entertainment',
        slug: 'streaming-entertainment',
        image: '/images/categories/streaming-subscriptions.jpg',
        icon: 'Play',
        productCount: 4,
      },
    ],
  },
  {
    id: 'gift-cards-wallet',
    title: 'Gift Cards & Wallet Top-Up',
    subtitle: 'Digital gift cards and prepaid options',
    labelKey: 'gift_cards_wallet',
    image: '/images/categories/gift-cards-wallet.jpg',
    categories: [
      {
        id: 'gift-cards',
        name: 'Gift Cards & Wallet Top-Up',
        slug: 'gift-cards-wallet',
        image: '/images/categories/gift-cards-topup.jpg',
        icon: 'Gift',
        productCount: 4,
      },
    ],
  },
  {
    id: 'software-saas',
    title: 'Software & SaaS Subscriptions',
    subtitle: 'Productivity and creative software',
    labelKey: 'software_saas',
    image: '/images/categories/software-saas.jpg',
    categories: [
      {
        id: 'software-subscriptions',
        name: 'Software & SaaS',
        slug: 'software-saas',
        image: '/images/categories/software-subscriptions.jpg',
        icon: 'Box',
        productCount: 5,
      },
    ],
  },
  {
    id: 'regional-services',
    title: 'Regional Digital Services',
    subtitle: 'Local OTT, streaming vouchers, and wallet top-ups',
    labelKey: 'regional_services',
    image: '/images/categories/regional-services.jpg',
    categories: [
      {
        id: 'regional-digital',
        name: 'Regional Digital Services',
        slug: 'regional-services',
        image: '/images/categories/regional-digital.jpg',
        icon: 'Zap',
        productCount: 3,
      },
    ],
  },
];

// ─── Products (each with unique image; USD base + optional priceByCurrency) ───

const aiDigitalProducts: Product[] = [
  {
    id: 'chatgpt-plus',
    name: 'ChatGPT Plus',
    description: 'Full access to GPT-4, DALL-E, and advanced features. Global availability.',
    price: 20.0,
    image: '/logos/chatgpt.png',
    category: 'ai-digital-tools',
    platform: 'OpenAI',
    region: 'Global',
    duration: 'Monthly',
    edition: 'Global',
    rating: 4.9,
    reviewCount: 5421,
    instantDelivery: true,
  },
  {
    id: 'claude-pro',
    name: 'Claude Pro',
    description: 'Access to Claude with higher limits and priority support.',
    price: 20.0,
    image: '/logos/claude.png',
    category: 'ai-digital-tools',
    platform: 'Anthropic',
    region: 'Global',
    duration: 'Monthly',
    edition: 'Global',
    rating: 4.8,
    reviewCount: 1892,
    instantDelivery: true,
  },
  {
    id: 'midjourney-standard',
    name: 'Midjourney Standard Plan',
    description: '15 hours GPU time with unlimited relax. AI image generation.',
    price: 30.0,
    image: '/logos/midjourney.png',
    category: 'ai-digital-tools',
    platform: 'Midjourney',
    region: 'Global',
    duration: 'Monthly',
    edition: 'Global',
    rating: 4.9,
    reviewCount: 2156,
    instantDelivery: true,
  },
  {
    id: 'cursor-pro',
    name: 'Cursor Pro',
    description: 'AI-first code editor with GPT-4 and Claude. Monthly subscription.',
    price: 20.0,
    image: '/logos/cursor.png',
    category: 'ai-digital-tools',
    platform: 'Cursor',
    region: 'Global',
    duration: 'Monthly',
    edition: 'Global',
    rating: 4.8,
    reviewCount: 2134,
    instantDelivery: true,
  },
  {
    id: 'perplexity-pro',
    name: 'Perplexity Pro',
    description: 'AI-powered search with real-time information and citations.',
    price: 20.0,
    image: '/logos/perplexity.png',
    category: 'ai-digital-tools',
    platform: 'Perplexity',
    region: 'Global',
    duration: 'Monthly',
    edition: 'Global',
    rating: 4.8,
    reviewCount: 876,
    instantDelivery: true,
  },
  {
    id: 'ai-api-credits',
    name: 'AI API Credits (100 credits)',
    description: '100 API credits for use across supported AI providers.',
    price: 25.0,
    image: '/logos/api.png',
    category: 'ai-digital-tools',
    platform: 'CrossMor',
    region: 'Global',
    duration: 'Credits',
    edition: 'Global',
    rating: 4.7,
    reviewCount: 432,
    instantDelivery: true,
  },
];

const streamingProducts: Product[] = [
  {
    id: 'netflix-1m',
    name: 'Netflix 1 Month',
    description: 'One month of Netflix Standard. Ad-free streaming.',
    price: 15.99,
    image: '/logos/netflix.png',
    category: 'streaming-entertainment',
    platform: 'Netflix',
    region: 'Global',
    duration: 'Monthly',
    edition: 'Global',
    rating: 4.9,
    reviewCount: 4234,
    instantDelivery: true,
  },
  {
    id: 'spotify-premium-1m',
    name: 'Spotify Premium 1 Month',
    description: 'One month Spotify Premium. Ad-free music and offline listening.',
    price: 10.99,
    image: '/logos/spotify.png',
    category: 'streaming-entertainment',
    platform: 'Spotify',
    region: 'Global',
    duration: 'Monthly',
    edition: 'Global',
    rating: 4.8,
    reviewCount: 1876,
    instantDelivery: true,
  },
  {
    id: 'youtube-premium-1m',
    name: 'YouTube Premium 1 Month',
    description: 'Ad-free YouTube with background play and downloads.',
    price: 11.99,
    image: '/logos/youtube.png',
    category: 'streaming-entertainment',
    platform: 'YouTube',
    region: 'Global',
    duration: 'Monthly',
    edition: 'Global',
    rating: 4.8,
    reviewCount: 2341,
    instantDelivery: true,
  },
  {
    id: 'disney-plus-1y',
    name: 'Disney+ 1 Year',
    description: '12 months of Disney+. Movies and series in one subscription.',
    price: 79.99,
    originalPrice: 99.99,
    image: '/logos/disney.png',
    category: 'streaming-entertainment',
    platform: 'Disney+',
    region: 'Global',
    duration: 'Yearly',
    edition: 'Global',
    rating: 4.7,
    reviewCount: 1543,
    badge: '20% OFF',
    instantDelivery: true,
  },
];

const giftCardsProducts: Product[] = [
  {
    id: 'apple-gift-card',
    name: 'Apple Gift Card',
    description: 'Use for App Store, iTunes, Apple Music, and more.',
    price: 25.0,
    image: '/logos/apple.png',
    category: 'gift-cards-wallet',
    platform: 'Apple',
    region: 'Global',
    duration: 'One-time',
    edition: 'Global',
    rating: 4.9,
    reviewCount: 6543,
    instantDelivery: true,
  },
  {
    id: 'google-play-gift-card',
    name: 'Google Play Gift Card',
    description: 'Redeem for apps, games, and digital content on Google Play.',
    price: 25.0,
    image: '/logos/googleplay.png',
    category: 'gift-cards-wallet',
    platform: 'Google',
    region: 'Global',
    duration: 'One-time',
    edition: 'Global',
    rating: 4.9,
    reviewCount: 4321,
    instantDelivery: true,
  },
  {
    id: 'amazon-gift-card',
    name: 'Amazon Gift Card',
    description: 'Universal Amazon gift card for millions of items.',
    price: 50.0,
    image: '/logos/amazon.png',
    category: 'gift-cards-wallet',
    platform: 'Amazon',
    region: 'Global',
    duration: 'One-time',
    edition: 'Global',
    rating: 4.9,
    reviewCount: 8765,
    instantDelivery: true,
  },
  {
    id: 'visa-prepaid-digital',
    name: 'Visa Prepaid Digital',
    description: 'Digital Visa prepaid card for online purchases.',
    price: 50.0,
    image: '/logos/visa.png',
    category: 'gift-cards-wallet',
    platform: 'Visa',
    region: 'Global',
    duration: 'One-time',
    edition: 'Global',
    rating: 4.8,
    reviewCount: 2100,
    instantDelivery: true,
  },
];

const softwareProducts: Product[] = [
  {
    id: 'microsoft-365',
    name: 'Microsoft 365',
    description: 'Office apps, 1TB OneDrive, and premium features. Annual plan.',
    price: 99.99,
    image: '/logos/microsoft.png',
    category: 'software-saas',
    platform: 'Microsoft',
    region: 'Global',
    duration: 'Yearly',
    edition: 'Global',
    rating: 4.8,
    reviewCount: 5432,
    instantDelivery: true,
  },
  {
    id: 'adobe-creative-cloud',
    name: 'Adobe Creative Cloud',
    description: 'Full access to Photoshop, Illustrator, Premiere Pro, and more.',
    price: 54.99,
    image: '/logos/adobe.png',
    category: 'software-saas',
    platform: 'Adobe',
    region: 'Global',
    duration: 'Monthly',
    edition: 'Global',
    rating: 4.7,
    reviewCount: 3210,
    instantDelivery: true,
  },
  {
    id: 'notion-plus',
    name: 'Notion Plus',
    description: 'Unlimited blocks, file uploads, and advanced collaboration.',
    price: 10.0,
    image: '/logos/notion.png',
    category: 'software-saas',
    platform: 'Notion',
    region: 'Global',
    duration: 'Monthly',
    edition: 'Global',
    rating: 4.8,
    reviewCount: 3456,
    instantDelivery: true,
  },
  {
    id: 'grammarly-premium',
    name: 'Grammarly Premium',
    description: 'Advanced writing suggestions and plagiarism detection.',
    price: 12.0,
    image: '/logos/grammarly.png',
    category: 'software-saas',
    platform: 'Grammarly',
    region: 'Global',
    duration: 'Monthly',
    edition: 'Global',
    rating: 4.7,
    reviewCount: 2876,
    instantDelivery: true,
  },
  {
    id: 'canva-pro',
    name: 'Canva Pro',
    description: 'Premium templates, brand kit, and AI design tools.',
    price: 12.99,
    image: '/logos/canva.png',
    category: 'software-saas',
    platform: 'Canva',
    region: 'Global',
    duration: 'Monthly',
    edition: 'Global',
    rating: 4.8,
    reviewCount: 5432,
    instantDelivery: true,
  },
];

const regionalProducts: Product[] = [
  {
    id: 'india-ott',
    name: 'India OTT Subscription',
    description: 'Popular Indian OTT platforms. Regional availability.',
    price: 14.99,
    image: '/logos/india.png',
    category: 'regional-services',
    platform: 'Regional',
    region: 'IN',
    duration: 'Monthly',
    edition: 'Global',
    rating: 4.6,
    reviewCount: 876,
    instantDelivery: true,
  },
  {
    id: 'brazil-streaming-voucher',
    name: 'Brazil Streaming Voucher',
    description: 'Streaming voucher for Brazil region. Redeem locally.',
    price: 29.99,
    image: '/logos/brazil.png',
    category: 'regional-services',
    platform: 'Regional',
    region: 'BR',
    duration: 'One-time',
    edition: 'Global',
    rating: 4.5,
    reviewCount: 432,
    instantDelivery: true,
  },
  {
    id: 'sea-wallet-topup',
    name: 'SEA Mobile Wallet Top-up',
    description: 'Mobile wallet top-up for Southeast Asia. Multiple providers.',
    price: 19.99,
    image: '/logos/sea.png',
    category: 'regional-services',
    platform: 'Regional',
    region: 'SEA',
    duration: 'One-time',
    edition: 'Global',
    rating: 4.6,
    reviewCount: 654,
    instantDelivery: true,
  },
];

// All products (for store.ts)
export const allProductsList: Product[] = [
  ...aiDigitalProducts,
  ...streamingProducts,
  ...giftCardsProducts,
  ...softwareProducts,
  ...regionalProducts,
];

// Featured for homepage / trending
export const featuredProducts: Product[] = [
  aiDigitalProducts[0],
  aiDigitalProducts[1],
  streamingProducts[0],
  streamingProducts[1],
  giftCardsProducts[0],
  softwareProducts[0],
  softwareProducts[1],
  regionalProducts[0],
];

// ─── Non-store data (testimonials, payment methods, etc.) ───────────────────
export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Alex Mueller',
    location: 'Germany',
    avatar: 'AM',
    content: 'Fastest digital delivery I\'ve ever used. Code arrived in my email within seconds. Highly recommended!',
    rating: 5,
  },
  {
    id: '2',
    name: 'Maria Silva',
    location: 'Brazil',
    avatar: 'MS',
    content: 'Finally a safe way to get ChatGPT Plus in my country. CrossMor handles everything professionally.',
    rating: 5,
  },
  {
    id: '3',
    name: 'James Wilson',
    location: 'United Kingdom',
    avatar: 'JW',
    content: 'The MOR model gives me peace of mind. I know I\'m dealing with a legitimate business.',
    rating: 5,
  },
  {
    id: '4',
    name: 'Yuki Tanaka',
    location: 'Japan',
    avatar: 'YT',
    content: 'Instant delivery, no hassle. The support team is also very responsive when I had questions.',
    rating: 5,
  },
  {
    id: '5',
    name: 'Carlos Rodriguez',
    location: 'Mexico',
    avatar: 'CR',
    content: 'Great prices on streaming and software. Saved over 20% compared to buying directly.',
    rating: 5,
  },
  {
    id: '6',
    name: 'Sophie Martin',
    location: 'France',
    avatar: 'SM',
    content: 'Customer support actually helps! Had an issue with my order and they resolved it within an hour.',
    rating: 5,
  },
];

export const paymentMethods: PaymentMethod[] = [
  { id: '1', name: 'Visa', icon: 'CreditCard' },
  { id: '2', name: 'Mastercard', icon: 'CreditCard' },
  { id: '3', name: 'PayPal', icon: 'Wallet' },
  { id: '4', name: 'Apple Pay', icon: 'Smartphone' },
  { id: '5', name: 'Google Pay', icon: 'Smartphone' },
  { id: '6', name: 'Alipay', icon: 'Wallet' },
  { id: '7', name: 'Crypto', icon: 'Bitcoin' },
];

export const stats = [
  { label: 'Happy Customers', value: 2, suffix: 'M+' },
  { label: 'Countries Served', value: 50, suffix: '+' },
  { label: 'Uptime', value: 99.9, suffix: '%', decimals: 1 },
  { label: 'Processed', value: 50, prefix: '$', suffix: 'M+' },
];

export const howItWorks = [
  {
    step: 1,
    title: 'Choose Your Product',
    description: 'Browse AI subscriptions, streaming, gift cards, and digital services',
    icon: 'Search',
  },
  {
    step: 2,
    title: 'Pay Securely',
    description: 'Multiple payment methods with encrypted transactions',
    icon: 'Shield',
  },
  {
    step: 3,
    title: 'Instant Delivery',
    description: 'Codes delivered to your email in seconds',
    icon: 'Zap',
  },
  {
    step: 4,
    title: 'Enjoy & Save',
    description: 'Activate and start using immediately',
    icon: 'Sparkles',
  },
];

export const trustFeatures = [
  {
    title: 'MOR Protection',
    description: 'We\'re the merchant of record, handling all tax and compliance for you.',
    icon: 'BadgeCheck',
  },
  {
    title: 'PCI DSS Compliant',
    description: 'Bank-level security for all transactions and data protection.',
    icon: 'Lock',
  },
  {
    title: 'Fraud Protection',
    description: 'AI-powered risk detection keeps your purchases safe.',
    icon: 'ShieldCheck',
  },
  {
    title: '24/7 Support',
    description: 'Real humans, real help, anytime you need assistance.',
    icon: 'Headphones',
  },
];
